package com.skyd.podaura.util.coil.localmedia

import kotlin.io.encoding.Base64

// Real short audio files with the same embedded green 64x32 PNG.
// WAV/AIFF/AAC/MP3 use ID3; FLAC/OGG/Opus use PICTURE; M4A/ALAC use MP4; WMA uses ASF.
internal val audioArtworkFixtures: Map<String, ByteArray> = buildMap {
    put(
        "mp3", Base64.decode(
            "SUQzBAAAAAABSVRTU0UAAAAPAAADTGF2ZjYyLjEyLjEwMgBBUElDAAABHAAAA2ltYWdlL3BuZwADAIlQTkcNChoKAAAADUlIRFIA" +
                    "AABAAAAAIAgCAAAALf/p0wAAAAlwSFlzAAAAAQAAAAEATyXE1gAAAEFJREFUeJztz8EJACAQwDAP3H9lHcJHEJoJ2lln1s+2DnjV" +
                    "gNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oB2ASfBAX6w2TxAAAAAAElFTkSuQmCCAAAAAAAAAAAAAP/7VMAAAAAAAAAAAAAA" +
                    "AAAAAAAAAEluZm8AAAAPAAAAAgAAAkAAqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqv//" +
                    "////////////////////////////////////////////////////////////////AAAAAExhdmM2Mi4yOAAAAAAAAAAAAAAAACQF" +
                    "0AAAAAAAAAJAbdE1HwAAAAAAAAAAAAAAAAAAAP/7VMQAA8AAAaQAAAAgAAA0gAAABExBTUUzLjEwMVVVVVVVVVVVVVVVVVVVVVVV" +
                    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
                    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7VMRV" +
                    "g8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
                    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
                    "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ=="
        )
    )
    put(
        "wav", Base64.decode(
            "UklGRgIDAABXQVZFZm10IBAAAAABAAEAgLsAAAB3AQACABAATElTVBoAAABJTkZPSVNGVA4AAABMYXZmNjIuMTIuMTAyAGRhdGHg" +
                    "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaWQzINMAAABJRDMEAAAAAAFJVFNTRQAAAA8AAANMYXZmNjIuMTIuMTAy" +
                    "AEFQSUMAAAEcAAADaW1hZ2UvcG5nAAMAiVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAACXBIWXMAAAABAAAAAQBP" +
                    "JcTWAAAAQUlEQVR4nO3PwQkAIBDAMA/cf2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgHYBJ8EB" +
                    "frDZPEAAAAAASUVORK5CYIIAAAAAAAAAAAAAAA=="
        )
    )
    put(
        "flac", Base64.decode(
            "ZkxhQwAAACISABIAAAAMAAAMC7gA8AAAAPCQlH40eRVFI/O98+okJTjIBgAAuAAAAAMAAAAJaW1hZ2UvcG5nAAAAAAAAAEAAAAAg" +
                    "AAAAGAAAAAAAAACPiVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAQUlEQVR4" +
                    "nO3PwQkAIBDAMA/cf2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgHYBJ8EBfrDZPEAAAAAASUVO" +
                    "RK5CYIKEAAAuDQAAAExhdmY2Mi4xMi4xMDIBAAAAFQAAAGVuY29kZXI9TGF2ZjYyLjEyLjEwMv/4aggA76QAAADLsw=="
        )
    )
    put(
        "aac", Base64.decode(
            "SUQzBAAAAAABSVRTU0UAAAAPAAADTGF2ZjYyLjEyLjEwMgBBUElDAAABHAAAA2ltYWdlL3BuZwADAIlQTkcNChoKAAAADUlIRFIA" +
                    "AABAAAAAIAgCAAAALf/p0wAAAAlwSFlzAAAAAQAAAAEATyXE1gAAAEFJREFUeJztz8EJACAQwDAP3H9lHcJHEJoJ2lln1s+2DnjV" +
                    "gNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oB2ASfBAX6w2TxAAAAAAElFTkSuQmCCAAAAAAAAAAAAAP/xTEADn/zeAgBMYXZj" +
                    "NjIuMjguMTAyAAIwQA7/8UxAAX/8ARggBw=="
        )
    )
    put(
        "ogg", Base64.decode(
            "T2dnUwACAAAAAAAAAADwJiyRAAAAAGMyQBMBHgF2b3JiaXMAAAAAAoC7AAAAAAAAAAAAAAAAAAC7AU9nZ1MAAAAAAAAAAAAA8CYs" +
                    "kQEAAADnV/t1D/9R////////////////uwN2b3JiaXMNAAAATGF2ZjYyLjEyLjEwMgIAAAAcAAAAZW5jb2Rlcj1MYXZjNjIuMjgu" +
                    "MTAyIHZvcmJpcw8BAABNRVRBREFUQV9CTE9DS19QSUNUVVJFPUFBQUFBd0FBQUFscGJXRm5aUzl3Ym1jQUFBQUFBQUFBUUFBQUFD" +
                    "QUFBQUFZQUFBQUFBQUFBSStKVUU1SERRb2FDZ0FBQUExSlNFUlNBQUFBUUFBQUFDQUlBZ0FBQUMzLzZkTUFBQUFKY0VoWmN3QUFB" +
                    "QUVBQUFBQkFFOGx4TllBQUFCQlNVUkJWSGljN2MvQkNRQWdFTUF3RDl4L1pSM0NSeENhQ2RwWlo5YlB0ZzU0MVlEV2dOYUExb0RX" +
                    "Z05hQTFvRFdnTmFBMW9EV2dOYUExb0RXZ05hQWRnRW53UUYrc05rOFFBQUFBQUJKUlU1RXJrSmdnZz09AQV2b3JiaXMcQkNWAgAQ" +
                    "AACEdJpZqgEizECGgdCQlQAAAgAAYIQiDDEgNGQlAAAQAAAghpKDaEJrzjfnOGiWg6ZSbE4HJ1JtnuSmYm7OOeecc7I5Z4xzzjmn" +
                    "KGcWg2ZCa845JzFoloJmQmvOOedJbB60pkprzjlnnHM6GGeEcc45p0lrHqRmY23OOWdBa5qj5lJszjknUm6e1OZSbc4555xzzjnn" +
                    "nHPOOad6cToH54Rzzjknam+u5SZ0cc4555NxujcnhHPOOeecc84555xzzjknCA1ZCQAAAQAQhGFjGHcKgvQ5GohRhJiGTHrQPTpM" +
                    "gsYgp5B6NDoaKaUOQkllnJTSCUJDVgIAgAAAEEJIIYUUUkghhRRSSCGFGGKIIYaccsopqKCSSiqqKKPMMssss8wyyyyzDjvrrMMO" +
                    "QwwxxNBKK7HUVFuNNdaae8655iCtldZaa62UUkoppZSC0JCVAAAIAACBkEEGGWQUUkghhRhiyimnnIIKKiA0ZCUAAAYAwCFnoIEG" +
                    "GmiggQYaaKBxxhmIIIIIIqikkkw6Cim12GrMMddegw46955777n4HIRSSimllFJKKaWUUkopJQgNWQkAgAAAAAghhBBSSCGFFFKK" +
                    "McYccw46CSUEQkNWAgBgAAAMMcQYZJBBSCGFGGKKKccccww6CCGUUlJooYVcaoglllZaiaWlmGqLsdZYc+0x1t5777333nvvvffe" +
                    "e86B0JCVAEAEAACDDCKIIIKMMQYhBISGrAQAQAAAEGKIMcYghBBSiCGnnIJMMumko5ACoSErAQAnAACEEUckcQQSZ6CBCCqpIKPM" +
                    "QiyxtdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmstEBqyEgCIAABgkEEGGUQQQQQZZIDQkJUAAAgAACOMQAQZpRRjjjnmGHTQ" +
                    "QScdhRZaIDRkJQDgBABAIKGIMswwBBFVVFFGFVUUUkcppZRSSimllFJKKaWUUkoppZRSSimllFJKKaVUSimlBEJDVgIAZAAAkKKU" +
                    "UiktRYIipRikGEtGFXNQWoqocgxSzalSziDmJJaIMYSUk1Qy5hRCDELqHHVMKQYtlRhCxhik2HJLoXMOCA1ZIQCEZgA4HAeQLAuQ" +
                    "LAsAAAAAAAAAJE0DNM8DLM0DAAAAAAAAAEnTAMvTAM3zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQNA3QPA/QPA8AAAAAAAAANM8DPE8EPFEEAAAAAAAAAMvzAE30AE8UAQAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQNA3QPA/QPA8AAAAAAAAA" +
                    "LM8DPFEENE8EAAAAAAAAAMvzAE8UAU/0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAACjgAAApYCIWGrAgA4gQAHJIESYIkQfMAkmVB06BpME2A" +
                    "ZFnQNGgaTBMAAAAAAAAAAAAASdOgadA0iCJA0jRoGjQNoggAAAAAAAAAAACApGnQNGgaRBEgaRo0DZoGUQQAAAAAAAAAAADAM02I" +
                    "IkQRpgnwTBOiCFGEaQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAACRwAAAVMKAOFhqwIAOIEAByOYlkAAOA4jmUBAIDjOJYFAACW" +
                    "ZYkiAABYliaKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC" +
                    "AAAJHAAABUwoA4WGrAQAogAAHIpiWcBxLAs4jmUBSbIsgGUBNA+gaQBRBAACAAANHAAABWzQlFgcoNCQlQBAFACAQXEsS9NEkSRp" +
                    "muaJIknSNM8TRZrmeZ5nmvA8zzNNiKIomiZEURRNE6ZpmqoKTFNVBQAAGjgAAArYoCmxOEChISsBgJAAAIeiWJameZ7niaJpqiZJ" +
                    "0jTPE0VRNE3TVFWSpGmeJ4qiaJqmqaosS9M8TxRF0TRVVVWhaZ4niqJomqqquvA8zxNFUTRNVXVdeJ7niaIomqaqui5EURRN0zRV" +
                    "U1VdF4iiaZqmqqqq6wLRE0XTVFXXdV3geaJomqrqqq4LRNM0VVVVXVeWAaZpmqrqurIMUFVVdV3XlWWAqqqq67quLANU1XVdV5Zl" +
                    "GYDruq4sy7IAAEAEBwBAASPoJKPKImw04cIDUGjIigAgCgAAMIYpxZQyjEkIKYSGMQkhhZBJSam0lCoIqZRUSgUhlZJKySillFpK" +
                    "FYRUSiqlgpBKSaUUAACL4AAAi2AhFBqyEgDIAwAgjFGKMcackwgpxZhzzkmElGLMOeekUow555xzUkrGHHPOOSmlc84555yUkjnn" +
                    "nHNOSumcc845J6WU0jnnnJNSSgmhc9BJKaV0zjnnBACAGjgAAArYKLI5wUhQoSErAYBUAACD41iWpnmeKJqmJUma5nmeJ4qmqUmS" +
                    "pnme54miavI8zxNFUTRNVeV5nieKomiaqsp1RdE0TVNVVZcsi6Jpmqaqui5M0zRV1XVdF6Zpmqrquq4L21ZVVXVdWYZtq6qquq4s" +
                    "A9d1XVm2ZSDLriu7tiwAAF7BAQDUwIbVEU6KxgILDVkJAGQAABDGIKQQQkgZhJBCCCGlFEICAAAJHAAABUwoA4WGrAQAUgEAAGOs" +
                    "tdZaa6010FlrrbXWWisgs9Zaa6211lprrbXWWmuttdRaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmut" +
                    "tdZaa6211lpLKaWUUkoppZRSSimllFJKKaWUUgFAvxYOAP8QNqyOcFI0FlhoyEoAIBwAADBGKcYcg1BKKRVCjDknHZXWYqwQYsw5" +
                    "CSm1FlvxnHMQSkiltRiL55yDUEpKsdVYVAqhlJRSiy3WolLoqKSUUms1FmNMKqm11mKrsRhjUgottdZijMUIW1NqLbbaaizG2JpK" +
                    "Cy3GGGMxwhcZW4uptlqDMcLIFktLtdYajDFG99Ziqa3mYowPvrYUS4w1FwDg7uAAgKhg4wwrSWeFo8GFhqwEAEICAAiElGKMMcac" +
                    "c845qRRjjjnnnIMQQiiVYowx55yDEEIIJWOMOecchBBCCKGUkjHnHIQQQgghpJQ65xyEEEIIIYRSSuecgxBCCCGEUErpIIQQQggh" +
                    "hBJKKSmFEEIIIYQQQioppRBCCKGUEEpIJaUUQgghhFBKCSmllEIIoZQQQighpZRSSiGEEEIppaSUUkqphFJCCaGEVEpKKYUSQgil" +
                    "lJJSSimVUkIooYRSSkkppZRSCCGEUkoBAIAIDgCAAkbQSUaVRdhowoUHIAAAAAQAIAiRGSJRsAAMDlQAQsIUAFBYYJADAA0OD2kX" +
                    "F9BlgAu6uOtACEEIQhCLAyggAQcn3PDEG55wgxN0ikoNCAAAAAAAGQB8AAAkD0BERDRzEBESExQVFhcYGRobHAAAgAACAAAQAAAA" +
                    "AAAIAAAAABBPZ2dTAAQAAQAAAAAAAPAmLJECAAAAIJl0HAIeHh4AAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAE" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        )
    )
    put(
        "m4a", Base64.decode(
            "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAAAIW1kYXTeAgBMYXZjNjIuMjguMTAyAAIwQA4BGCAHAAADqm1v" +
                    "b3YAAABsbXZoZAAAAAAAAAAAAAAAAAAAA+gAAAAFAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA" +
                    "AAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAItdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAF" +
                    "AAAAAAAAAAAAAAABAQAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAJGVkdHMAAAAcZWxz" +
                    "dAAAAAAAAAABAAAABQAABAAAAQAAAAABpW1kaWEAAAAgbWRoZAAAAAAAAAAAAAAAAAAAu4AAAATwVcQAAAAAAC1oZGxyAAAAAAAA" +
                    "AABzb3VuAAAAAAAAAAAAAAAAU291bmRIYW5kbGVyAAAAAVBtaW5mAAAAEHNtaGQAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAA" +
                    "AAAAAQAAAAx1cmwgAAAAAQAAARRzdGJsAAAAanN0c2QAAAAAAAAAAQAAAFptcDRhAAAAAAAAAAEAAAAAAAAAAAABABAAAAAAu4AA" +
                    "AAAAADZlc2RzAAAAAAOAgIAlAAEABICAgBdAFQAAAAABDYgAAB2qBYCAgAURiFblAAaAgIABAgAAACBzdHRzAAAAAAAAAAIAAAAB" +
                    "AAAEAAAAAAEAAADwAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAACAAAAAQAAABxzdHN6AAAAAAAAAAAAAAACAAAAFQAAAAQAAAAUc3Rj" +
                    "bwAAAAAAAAABAAAALAAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAACAAAAAQAAAQl1ZHRh" +
                    "AAABAW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAA1Glsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAA" +
                    "AABMYXZmNjIuMTIuMTAyAAAAp2NvdnIAAACfZGF0YQAAAA4AAAAAiVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAA" +
                    "CXBIWXMAAAABAAAAAQBPJcTWAAAAQUlEQVR4nO3PwQkAIBDAMA/cf2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA" +
                    "1oDWgNaA1oDWgHYBJ8EBfrDZPEAAAAAASUVORK5CYII="
        )
    )
    put(
        "wma", Base64.decode(
            "MCaydY5mzxGm2QCqAGLObLQCAAAAAAAABQAAAAECodyrjEepzxGO5ADADCBTZWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGYPAAAA" +
                    "AAAAAIA+1d6xnQEBAAAAAAAAABDJ2QEAAAAAUMMAAAAAAAAcDAAAAAAAAAIAAACADAAAgAwAAAD0AQC1A79fLqnPEY7jAMAMIFNl" +
                    "LgAAAAAAAAAR0tOruqnPEY7mAMAMIFNlBgAAAAAAQKTQ0gfj0hGX8ACgyV6oUCoBAAAAAAAAAgAoAFcATQAvAEUAbgBjAG8AZABp" +
                    "AG4AZwBTAGUAdAB0AGkAbgBnAHMAAAAAABwATABhAHYAZgA2ADIALgAxADIALgAxADAAMgAAABYAVwBNAC8AUABpAGMAdAB1AHIA" +
                    "ZQAAAAEAqgADjwAAAGkAbQBhAGcAZQAvAHAAbgBnAAAAAACJUE5HDQoaCgAAAA1JSERSAAAAQAAAACAIAgAAAC3/6dMAAAAJcEhZ" +
                    "cwAAAAEAAAABAE8lxNYAAABBSURBVHic7c/BCQAgEMAwD9x/ZR3CRxCaCdpZZ9bPtg541YDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA" +
                    "1oDWgNaAdgEnwQF+sNk8QAAAAABJRU5ErkJggpEH3Le3qc8RjuYAwAwgU2VyAAAAAAAAAECeafhNW88RqP0AgF9cRCtQzcO/j2HP" +
                    "EYuyAKoAtOIgAAAAAAAAAAAcAAAACAAAAAEAAAAAAGEBAQCAuwAAgD4AAKoCEAAKAAAAAAABAAAAAAABqgKqAgEAAEBS0YYdMdAR" +
                    "o6QAoMkDSPZkAAAAAAAAAEFS0YYdMdARo6QAoMkDSPYBAAAAAgAXAFcAaQBuAGQAbwB3AHMAIABNAGUAZABpAGEAIABBAHUAZABp" +
                    "AG8AIABWADgAAAAAAAIAYQE2JrJ1jmbPEabZAKoAYs5ssgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAYIAABFdtwkA" +
                    "AAAAAACBAQEAAAAACKoCAAAcDAAAqgKA/0AAAAeATk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5O" +
                    "Tk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        )
    )
    put(
        "opus", Base64.decode(
            "T2dnUwACAAAAAAAAAACGO6UwAAAAAFzpYB8BE09wdXNIZWFkAQE4AYC7AAAAAABPZ2dTAAAAAAAAAAAAAIY7pTABAAAAXsS2HAL/" +
                    "Uk9wdXNUYWdzDQAAAExhdmY2Mi4xMi4xMDICAAAAHQAAAGVuY29kZXI9TGF2YzYyLjI4LjEwMiBsaWJvcHVzDwEAAE1FVEFEQVRB" +
                    "X0JMT0NLX1BJQ1RVUkU9QUFBQUF3QUFBQWxwYldGblpTOXdibWNBQUFBQUFBQUFRQUFBQUNBQUFBQVlBQUFBQUFBQUFJK0pVRTVI" +
                    "RFFvYUNnQUFBQTFKU0VSU0FBQUFRQUFBQUNBSUFnQUFBQzMvNmRNQUFBQUpjRWhaY3dBQUFBRUFBQUFCQUU4bHhOWUFBQUJCU1VS" +
                    "QlZIaWM3Yy9CQ1FBZ0VNQXdEOXgvWlIzQ1J4Q2FDZHBaWjliUHRnNTQxWURXZ05hQTFvRFdnTmFBMW9EV2dOYUExb0RXZ05hQTFv" +
                    "RFdnTmFBZGdFbndRRitzTms4UUFBQUFBQkpSVTVFcmtKZ2dnPT1PZ2dTAAQoAgAAAAAAAIY7pTACAAAAt3LGlgED+P/+"
        )
    )
    put(
        "alac", Base64.decode(
            "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAAAH21kYXQAABAAAAHgAAAPCAEAAAAAAAAA/4B38AAAA1Jtb292" +
                    "AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAABQABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA" +
                    "AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAB1XRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAABQAA" +
                    "AAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QA" +
                    "AAAAAAAAAQAAAAUAAAAAAAEAAAAAAU1tZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAALuAAAAA8FXEAAAAAAAtaGRscgAAAAAAAAAA" +
                    "c291bgAAAAAAAAAAAAAAAFNvdW5kSGFuZGxlcgAAAAD4bWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAA" +
                    "AAEAAAAMdXJsIAAAAAEAAAC8c3RibAAAAFhzdHNkAAAAAAAAAAEAAABIYWxhYwAAAAAAAAABAAAAAAAAAAAAAQAQAAAAALuAAAAA" +
                    "AAAkYWxhYwAAAAAAABAAABAoCg4BAAAAACAEAAu4AAAAu4AAAAAYc3R0cwAAAAAAAAABAAAAAQAAAPAAAAAcc3RzYwAAAAAAAAAB" +
                    "AAAAAQAAAAEAAAABAAAAFHN0c3oAAAAAAAAAFwAAAAEAAAAUc3RjbwAAAAAAAAABAAAALAAAAQl1ZHRhAAABAW1ldGEAAAAAAAAA" +
                    "IWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAA1Glsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjIuMTIuMTAy" +
                    "AAAAp2NvdnIAAACfZGF0YQAAAA4AAAAAiVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAACXBIWXMAAAABAAAAAQBP" +
                    "JcTWAAAAQUlEQVR4nO3PwQkAIBDAMA/cf2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgHYBJ8EB" +
                    "frDZPEAAAAAASUVORK5CYII="
        )
    )
    put(
        "aiff", Base64.decode(
            "Rk9STQAAAupBSUZGQ09NTQAAABIAAQAAAPAAEEAOu4AAAAAAAABTU05EAAAB6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
                    "AAAAAAAAAAAASUQzIAAAANNJRDMEAAAAAAFJVFNTRQAAAA8AAANMYXZmNjIuMTIuMTAyAEFQSUMAAAEcAAADaW1hZ2UvcG5nAAMA" +
                    "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAQUlEQVR4nO3PwQkAIBDAMA/c" +
                    "f2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgHYBJ8EBfrDZPEAAAAAASUVORK5CYIIAAAAAAAAA" +
                    "AAAAAA=="
        )
    )
    put("aif", getValue("aiff"))
}

internal val audioArtworkPng = Base64.decode(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAIAAAAt/+nTAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAQUlEQVR4nO3PwQkAIBDAMA/cf2UdwkcQmgnaWWfWz7YOeNWA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgNaA1oDWgHYBJ8EBfrDZPEAAAAAASUVORK5CYII="
)
