package com.skyd.podaura.util.coil.localmedia

import kotlin.io.encoding.Base64

// Shared by native macOS and iOS: red before 1s, green from 1s onward; 10% must produce green.
internal val videoThumbnailFixture: ByteArray
    get() = Base64.decode(
        "GkXfo6NChoEBQveBAULygQRC84EIQoKIbWF0cm9za2FCh4EEQoWBAhhTgGcBAAAAAAAHBxFNm3TAv4Qkq8RQTbuLU6uEFUmp" +
        "ZlOsgaFNu4tTq4QWVK5rU6yB8U27jFOrhBJUw2dTrIIBhU27jFOrhBxTu2tTrIIGQ+wBAAAAAAAAUwAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFUmp" +
        "Zsu/hAEG82Uq17GDD0JATYCNTGF2ZjYyLjEyLjEwMldBjUxhdmY2Mi4xMi4xMDJzpJCWaRB10ZIWUGOAvYGP8JlMRImIQMOI" +
        "AAAAAAAWVK5rQI6/hFKb8YCuAQAAAAAAAH/XgQFzxYg31+qh3Oy235yBACK1nIN1bmSIgQCGj1ZfTVBFRzQvSVNPL0FWQ4OB" +
        "ASPjg4QdzWUA4JCwgRC6gRCagQJVsIRVuYEBVe6BAOwBAAAAAAAAAgAAY6KkAULACv/hABVnQsAK2nsBEAAAAwAQAAADAEDx" +
        "ImoBAARozg/IElTDZ0CDv4Qf8a4Pc3OgY8CAZ8iaRaOHRU5DT0RFUkSHjUxhdmY2Mi4xMi4xMDJzc9djwItjxYg31+qh3Oy2" +
        "32fIokWjh0VOQ09ERVJEh5VMYXZjNjIuMjguMTAyIGxpYngyNjRnyKFFo4hEVVJBVElPTkSHkzAwOjAwOjEwLjAwMDAwMDAw" +
        "MAAfQ7Z1Q1y/hBRrQ7jngQCjQnCBAACAAAACUQYF//9N3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIyMiBi" +
        "MzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cudmlkZW9s" +
        "YW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTAgcmVmPTEgZGVibG9jaz0wOjA6MCBhbmFseXNlPTA6MCBtZT1k" +
        "aWEgc3VibWU9MCBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRy" +
        "ZWxsaXM9MCA4eDhkY3Q9MCBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0wIHRo" +
        "cmVhZHM9MSBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9" +
        "MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTAgd2VpZ2h0cD0wIGtleWludD0yIGtleWlu" +
        "dF9taW49MSBzY2VuZWN1dD0wIGludHJhX3JlZnJlc2g9MCByYz1jcmYgbWJ0cmVlPTAgY3JmPTIzLjAgcWNvbXA9MC42MCBx" +
        "cG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAgYXE9MACAAAAAE2WIhDoRigACGPHAAED2OAAIeWCjjYEB" +
        "9AAAAAAFQZogEqWjnIED6IAAAAAUZYiCAyhGKAAIaEcAAR644AAk84CjjYEF3AAAAAAFQZogEqWjm4EH0IAAAAATZYiEDqEY" +
        "oAAiKRwABKBjgACZvqONgQnEAAAAAAVBmiASpaOcgQu4gAAAABRliIIBChGKAAItUcAATN44AAoQ4KONgQ2sAAAAAAVBmiAS" +
        "paOcgQ+ggAAAABRliIQEKEYoAAi1RwABM3jgAChDgKONgRGUAAAAAAVBmiASpaOcgROIgAAAABRliIIBGhGKAAIyEcAATjY4" +
        "AApG4B9DtnVAzb+EtNrnLueCFXyjjYEAAAAAAAAFQZogEqWjnIEB9IAAAAAUZYiEBGhGKAAIyEcAATjY4AApG4CjjYED6AAA" +
        "AAAFQZogEqWjnIEF3IAAAAAUZYiCASoRigACOFHAAE/WOAAKiOCjjYEH0AAAAAAFQZogEqWjnIEJxIAAAAAUZYiEBKhGKAAI" +
        "4UcAAT9Y4AAqI4CjjYELuAAAAAAFQZogEqWjnIENrIAAAAAUZYiCASoRigACOFHAAE/WOAAKiOCjjYEPoAAAAAAFQZogEqUc" +
        "U7trQL6/hKRAKkG7j7OBALeK94EB8YICDvCBCbuRs4ID6LeL94EB8YICDvCCAou7kbOCB9C3i/eBAfGCAg7wggK4u5Gzggu4" +
        "t4v3gQHxggIO8IIC5LuRs4IPoLeL94EB8YICDvCCAxG7kbOCE4i3i/eBAfGCAg7wggM+u5Czghdwt4r3gQHxggVw8IEZu5Cz" +
        "ghtYt4r3gQHxggVw8IFGu5Czgh9At4r3gQHxggVw8IFzu5CzgiMot4r3gQHxggVw8IGg"
    )
